### ISSUE TITLE
The discord link is dead

### ISSUE THREAD

**Issue by amoutiers** [blackfyre/flsun.community#5]
Hello,

Having a lokk to buy a Flsun printer, but before see if there's a community around it.
I've seen your hub, which is great idea.
But the discord link provided on this page https://flsun.community/guide/social-media.html won't work

Best regards

**Comment by djekl** [comment]
You can create discord links that never expire. Here is the support page - [https://support.discord.com/hc/en-us/articles/208866998-Invites-101](https://support.discord.com/hc/en-us/articles/208866998-Invites-101)

**Comment by blackfyre** [comment]
Yeah, found that a couple minutes after the comment.
This issue was closed with https://github.com/blackfyre/flsun.community/commit/66be4f53c6631f147884e1545d03b026f833ba76
