### ISSUE TITLE
New links for the Delta Foxies firmware ;-)

### ISSUE THREAD

**Issue by Foxies-CSTL** [blackfyre/flsun.community#6]
Hi @blackfyre ,
Just to let you know that my links to the firmwares and documentation have changed:
Wiki: https://github.com/Foxies-CSTL/Marlin_2.0.x/wiki
Firmwares: https://github.com/Foxies-CSTL/Marlin_2.0.x/tree/Firmwares
See you later,

**Comment by blackfyre** [comment]
Will update it asap 😁
